### ISSUE TITLE
Cannot update to 0.1.5.3

### ISSUE THREAD

**Issue by mscrivo** [yohasebe/ruby-spacy#3]
Thanks for fixing the WEBrick dep vulnerability! 

However, when trying to update to the new version, it seems something is off as I'm getting the following error:

```
Could not find gem 'ruby-spacy' with platform 'ruby' in rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'ruby-spacy':
  * ruby-spacy-0.1.0
  * ruby-spacy-0.1.1
  * ruby-spacy-0.1.2
  * ruby-spacy-0.1.3
  * ruby-spacy-0.1.4
  * ruby-spacy-0.1.4.1
  * ruby-spacy-0.1.5.0
  * ruby-spacy-0.1.5.1
  * ruby-spacy-0.1.5.2
```

This is after manually changing it from 0.1.5.2 in our Gemfile.lock to 0.1.5.3, since `bundle update ruby-spacy` was not finding it either.

We're using ruby 3.2.2 FWIW

**Comment by yohasebe** [comment]
I have confirmed the issue with installing version 0.1.5.3 via Rubygems. Could you please try version 0.1.5.4? I believe this version resolves the error. Thank you for reporting it!

**Comment by mscrivo** [comment]
Working great, thank you!
