### ISSUE TITLE
Question: Possible to use spacy llm from ruby-spacy?

### ISSUE THREAD

**Issue by mscrivo** [yohasebe/ruby-spacy#4]
Hi @yohasebe, hope you are well.

No rush on this, but was wondering if it's at all possible to setup and invoke the newish [spacy llm stuff](https://spacy.io/usage/large-language-models) from ruby-spacy?

**Comment by yohasebe** [comment]
Thank you for reaching out. I'm certainly watching recent developments related to LLM features in SpaCy.

At this time, I'm uncertain whether ruby-spacy should directly leverage SpaCy's native functionality for LLMs, given the potential overhead. It might be more straightforward to implement similar features directly in Ruby.

Please feel free to let me know if you have any use cases or suggestions regarding integration with LLMs.

**Comment by mscrivo** [comment]
No specific use cases yet, just wondering if it was possible really.
